spring:
  application:
    name: question
  datasource:
    url: jdbc:postgresql://localhost:5432/questiondb

  cloud:
    function:
      definition: commandResponseChannel;questionServiceCommandChannel;questionEventSubscriber;
    stream:
      bindings:
        question-command-channel:
          destination: question-command-channel
        questionServiceCommandChannel-in-0:
          destination: question-command-channel
          group: question-service-group
        commandResponseChannel-in-0:
          destination: question-command-responses
          group: question-response-group
        questionEventSubscriber-in-0:
          destination: event-channel
          group: question-service-group

server:
  port: 8084

---
spring:
  config:
    activate:
      on-profile: "!kubernetes"
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
