spring:
  application:
    name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb

  cloud:
    function:
      definition: commandResponseChannel;userServiceCommandChannel;userEventSubscriber;
    stream:
      bindings:
        user-command-channel:
          destination: user-command-channel
        userServiceCommandChannel-in-0:
          destination: user-command-channel
          group: user-service-group
        commandResponseChannel-in-0:
          destination: user-command-responses
          group: user-response-group
        userEventSubscriber-in-0:
          destination: event-channel
          group: user-service-group

server:
  port: 8088

---
spring:
  config:
    activate:
      on-profile: "!kubernetes"
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
