spring:
  application:
    name: course-execution
  datasource:
    url: jdbc:postgresql://localhost:5432/executiondb

  cloud:
    function:
      definition: commandResponseChannel;courseExecutionServiceCommandChannel;courseExecutionEventSubscriber;
    stream:
      bindings:
        course-execution-command-channel:
          destination: courseExecution-command-channel
        courseExecutionServiceCommandChannel-in-0:
          destination: courseExecution-command-channel
          group: course-execution-service-group
        commandResponseChannel-in-0:
          destination: course-execution-command-responses
          group: course-execution-response-group
        courseExecutionEventSubscriber-in-0:
          destination: event-channel
          group: course-execution-service-group

server:
  port: 8083
