spring:
  application:
    name: answer
  datasource:
    url: jdbc:postgresql://localhost:5432/answerdb

  cloud:
    function:
      definition: commandResponseChannel;answerServiceCommandChannel;answerEventSubscriber;
    stream:
      bindings:
        answer-command-channel:
          destination: answer-command-channel
        answerServiceCommandChannel-in-0:
          destination: answer-command-channel
          group: answer-service-group
        commandResponseChannel-in-0:
          destination: answer-command-responses
          group: answer-response-group
        answerEventSubscriber-in-0:
          destination: event-channel
          group: answer-service-group

server:
  port: 8082