spring:
  application:
    name: answer
  datasource:
    url: jdbc:postgresql://localhost:5432/answerdb

  cloud:
    function:
      definition: commandResponseChannel;answerServiceCommandChannel;answerEventSubscriber;
    stream:
      bindings:
        answer-command-channel:
          destination: answer-command-channel
        answerServiceCommandChannel-in-0:
          destination: answer-command-channel
          group: answer-service-group
        commandResponseChannel-in-0:
          destination: answer-command-responses
          group: answer-response-group
        answerEventSubscriber-in-0:
          destination: event-channel
          group: answer-service-group

server:
  port: 8082
grpc:
  server:
    port: 9092

---
spring:
  config:
    activate:
      on-profile: "!kubernetes"
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
    metadata-map:
      grpcPort: ${grpc.server.port}
