spring:
  application:
    name: topic
  datasource:
    url: jdbc:postgresql://localhost:5432/topicdb

  cloud:
    function:
      definition: commandResponseChannel;topicServiceCommandChannel;topicEventSubscriber;
    stream:
      bindings:
        topic-command-channel:
          destination: topic-command-channel
        topicServiceCommandChannel-in-0:
          destination: topic-command-channel
          group: topic-service-group
        commandResponseChannel-in-0:
          destination: topic-command-responses
          group: topic-response-group
        topicEventSubscriber-in-0:
          destination: event-channel
          group: topic-service-group

server:
  port: 8086
grpc:
  server:
    port: 9096

---
spring:
  config:
    activate:
      on-profile: "!kubernetes"
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
    metadata-map:
      grpcPort: ${grpc.server.port}
