spring:
  application:
    name: quiz
  datasource:
    url: jdbc:postgresql://localhost:5432/quizdb

  cloud:
    function:
      definition: commandResponseChannel;quizServiceCommandChannel;quizEventSubscriber;
    stream:
      bindings:
        quiz-command-channel:
          destination: quiz-command-channel
        quizServiceCommandChannel-in-0:
          destination: quiz-command-channel
          group: quiz-service-group
        commandResponseChannel-in-0:
          destination: quiz-command-responses
          group: quiz-response-group
        quizEventSubscriber-in-0:
          destination: event-channel
          group: quiz-service-group

server:
  port: 8085
grpc:
  server:
    port: 9095

---
spring:
  config:
    activate:
      on-profile: "!kubernetes"
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
    metadata-map:
      grpcPort: ${grpc.server.port}
