spring:
  application:
    name: tournament
  datasource:
    url: jdbc:postgresql://localhost:5432/tournamentdb

  cloud:
    discovery:
      enabled: true
    function:
      definition: commandResponseChannel;tournamentServiceCommandChannel;tournamentEventSubscriber;
    stream:
      bindings:
        tournament-command-channel:
          destination: tournament-command-channel
        tournamentServiceCommandChannel-in-0:
          destination: tournament-command-channel
          group: tournament-service-group
        commandResponseChannel-in-0:
          destination: tournament-command-responses
          group: tournament-response-group
        tournamentEventSubscriber-in-0:
          destination: event-channel
          group: tournament-service-group

server:
  port: 8087

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
