apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: microservices-simulator
data:
  SPRING_PROFILES_ACTIVE: "kubernetes,sagas,stream"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"
  DB_USERNAME: "postgres"
  DB_PASSWORD: "postgres"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: microservices-simulator
data:
  POSTGRES_DB: "msdb"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
