server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Course Execution Service (User Executions)
            - id: course-execution-service-users
              uri: http://${COURSE_EXECUTION_SERVICE_HOST:localhost}:8083
              predicates:
                - Path=/users/*/executions

            # User Service
            - id: user-service
              uri: http://${USER_SERVICE_HOST:localhost}:8088
              predicates:
                - Path=/users/**

            # Topic Service
            - id: topic-service
              uri: http://${TOPIC_SERVICE_HOST:localhost}:8086
              predicates:
                - Path=/courses/*/topics/**, /courses/*/create, /topics/**

            # Question Service
            - id: question-service
              uri: http://${QUESTION_SERVICE_HOST:localhost}:8084
              predicates:
                - Path=/questions/**, /courses/*/questions/**

            # Answer Service
            - id: answer-service
              uri: http://${ANSWER_SERVICE_HOST:localhost}:8082
              predicates:
                - Path=/quizzes/*/answer

            # Tournament Service
            - id: tournament-service
              uri: http://${TOURNAMENT_SERVICE_HOST:localhost}:8087
              predicates:
                - Path=/tournaments/**, /executions/*/tournaments/**, /tournament/**

            # Quiz Service
            - id: quiz-service
              uri: http://${QUIZ_SERVICE_HOST:localhost}:8085
              predicates:
                - Path=/quizzes/**

            # Execution Routes (Ordered)
            - id: course-execution-service-create
              uri: http://${COURSE_EXECUTION_SERVICE_HOST:localhost}:8083
              predicates:
                - Path=/executions/create

            - id: quiz-service-execution-post
              uri: http://${QUIZ_SERVICE_HOST:localhost}:8085
              predicates:
                - Method=POST
                - Path=/executions/{executionId}

            - id: course-execution-service
              uri: http://${COURSE_EXECUTION_SERVICE_HOST:localhost}:8083
              predicates:
                - Path=/executions/**

logging:
  level:
    org.springframework.cloud.gateway: ${GATEWAY_LOG_LEVEL:TRACE}
    org.springframework.web.reactive: ${REACTIVE_LOG_LEVEL:DEBUG}
    org.springframework.core.io.buffer: ${BUFFER_LOG_LEVEL:DEBUG}