server:
  port: 8080

gateway:
  service-suffix: ""
  exclude-services: gateway

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
    register-with-eureka: false
    fetch-registry: true
    registry-fetch-interval-seconds: 15
  instance:
    prefer-ip-address: true

version-service: http://${VERSION_SERVICE_HOST:localhost}:8081

spring:
  application:
    name: gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      server:
        webflux:
          routes:
            # Course Execution Service (User Executions)
            - id: courseExecution-service-users
              uri: lb://courseExecution${gateway.service-suffix}
              predicates:
                - Path=/users/*/executions

            # User Service
            - id: user-service
              uri: lb://user${gateway.service-suffix}
              predicates:
                - Path=/users/**

            # Topic Service
            - id: topic-service
              uri: lb://topic${gateway.service-suffix}
              predicates:
                - Path=/courses/*/topics/**, /courses/*/create, /topics/**

            # Question Service
            - id: question-service
              uri: lb://question${gateway.service-suffix}
              predicates:
                - Path=/questions/**, /courses/*/questions/**

            # Answer Service
            - id: answer-service
              uri: lb://answer${gateway.service-suffix}
              predicates:
                - Path=/quizzes/*/answer

            # Tournament Service
            - id: tournament-service
              uri: lb://tournament${gateway.service-suffix}
              predicates:
                - Path=/tournaments/**, /executions/*/tournaments/**, /tournament/**

            # Quiz Service
            - id: quiz-service
              uri: lb://quiz${gateway.service-suffix}
              predicates:
                - Path=/quizzes/**

            # Execution Routes (Ordered)
            - id: courseExecution-service-create
              uri: lb://courseExecution${gateway.service-suffix}
              predicates:
                - Path=/executions/create

            - id: quiz-service-execution-post
              uri: lb://quiz${gateway.service-suffix}
              predicates:
                - Method=POST
                - Path=/executions/{executionId}

            - id: courseExecution-service
              uri: lb://courseExecution${gateway.service-suffix}
              predicates:
                - Path=/executions/**

logging:
  level:
    org.springframework.cloud.gateway: ${GATEWAY_LOG_LEVEL:TRACE}
    org.springframework.web.reactive: ${REACTIVE_LOG_LEVEL:DEBUG}
    org.springframework.core.io.buffer: ${BUFFER_LOG_LEVEL:DEBUG}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
