server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Course Execution Service (User Executions) - Must be before User Service
            - id: course-execution-service-users
              uri: http://course-execution-service:8083
              predicates:
                - Path=/users/*/executions

            # User Service
            - id: user-service
              uri: http://user-service:8088
              predicates:
                - Path=/users/**

            # Topic Service
            - id: topic-service
              uri: http://topic-service:8086
              predicates:
                - Path=/courses/*/topics/**, /courses/*/create, /topics/**

            # Question Service
            - id: question-service
              uri: http://question-service:8084
              predicates:
                - Path=/questions/**, /courses/*/questions/**

            # Answer Service
            - id: answer-service
              uri: http://answer-service:8082
              predicates:
                - Path=/quizzes/*/answer

            # Tournament Service
            - id: tournament-service
              uri: http://tournament-service:8087
              predicates:
                - Path=/tournaments/**, /executions/*/tournaments/**

            # Quiz Service
            - id: quiz-service
              uri: http://quiz-service:8085
              predicates:
                - Path=/quizzes/**

            # Execution Routes (Ordered)
            - id: course-execution-service-create
              uri: http://course-execution-service:8083
              predicates:
                - Path=/executions/create

            - id: quiz-service-execution-post
              uri: http://quiz-service:8085
              predicates:
                - Method=POST
                - Path=/executions/{executionId}

            - id: course-execution-service
              uri: http://course-execution-service:8083
              predicates:
                - Path=/executions/**

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web.reactive: INFO
