apiVersion: v1
kind: Service
metadata:
  name: question-service
  namespace: microservices-simulator
spec:
  selector:
    app: question-service
  ports:
    - port: 8084
      targetPort: 8084
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service
  namespace: microservices-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-service
  template:
    metadata:
      labels:
        app: question-service
    spec:
      serviceAccountName: microservices-sa
      containers:
        - name: question-service
          image: quizzes-question:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes,question-service,sagas,stream"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/questiondb"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 10
